export const animation = {
	flipInX:(node,done)=>{
		node.classList.add('animated','flipInX')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','flipInX')
		})
	},
	flipInY:(node,done)=>{
		node.classList.add('animated','flipInY')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','flipInY')
		})
	},
	flip:(node,done)=>{
		node.classList.add('animated','flip')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','flip')
		})
	},
	jello:(node,done)=>{
		node.classList.add('animated','jello')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','jello')
		})
	},
	rotateIn:(node,done)=>{
		node.classList.add('animated','rotateIn')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','rotateIn')
		})
	},
	rollIn:(node,done)=>{
		node.classList.add('animated','rollIn')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','rollIn')
		})
	},
	rubberBand:(node,done)=>{
		node.classList.add('animated','rubberBand')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','rubberBand')
		})
	},
	fadeInDown:(node,done)=>{
		node.classList.add('animated','fadeInDown','shorten')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','fadeInDown','shorten')
		})
	},
	bounceOut:(node,done)=>{
		node.classList.add('animated','bounceOut')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','bounceOut')
		})
	},
	fadeOutDown:(node,done)=>{
		node.classList.add('animated','fadeOutDown','shorten')
		node.addEventListener('animationend',()=>{
			done();
			node.classList.remove('animated','fadeOutDown','shorten')
		})
	},

}
